### ISSUE TITLE
Make a script to regenerate Rust protobuf files

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3147]
Right now you have to run `cargo run --bin protobuf-gen tools/protobuf_files.toml` which is pretty hard to remember, we should make a [small helper script for that](https://github.com/mozilla/application-services/blob/87e910cd79e4ee64809a7a85c07c7fd6a6da6a03/automation/check_protobuf_files_current.py#L9-L12).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1329)
┆Story Points: 2
┆Epic: important not urgent
┆Sprint: SYNC - end 2020-06-05

**Comment by thomcc** [comment]
https://doc.rust-lang.org/cargo/reference/config.html#alias is probably a thing we could use here...

```toml
[alias]
regen-protobufs = ["run", "--bin", "protobuf-gen", "tools/protobuf_files.toml"]
```
