### ISSUE TITLE
Add sccache to nimbus-fml build on circle-ci

### ISSUE THREAD

**Issue by jhugman** [mozilla/application-services#4731]
_Originally posted by @tarikeshaq in https://github.com/mozilla/application-services/pull/4701#discussion_r768868181_

Definitely for a follow up... Probably not be worth it unless the fml takes a long time to compile, which it doesn't now - 5 mins is not bad at all:

We might be able to cut down some CI time by using `sccache`:
```yaml
- restore_cache:
    name: Restore sccache cache
    key: fml-sccache-cache-macos-{{ arch }}
- full-checkout
- install rust
- setup-rust-target-version
- setup-sccache

.. rest of commands
- save_cache:
    name: Save sccache cache
    key: fml-sccache-cache-macos-{{ arch }}-{{ epoch }}
    paths:
      - "~/Library/Caches/Mozilla.sccache"
- sccache-stats-and-logs
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2073)
